package com.learn-git-by-building-an-sql-reference-object

data class User(
    val id: String,
    val name: String,
    val email: String
)

class main {
    private val users = mutableListOf<User>()

    fun initialize() {
        println("Initializing learn-git-by-building-an-sql-reference-object")
        users.add(User("1", "John Doe", "john@example.com"))
        users.add(User("2", "Jane Smith", "jane@example.com"))
    }

    fun run() {
        println("Welcome to learn-git-by-building-an-sql-reference-object")
        println("Users:")
        users.forEach { user ->
            println("- \${user.name} (\${user.email})")
        }
    }

    fun addUser(user: User) {
        users.add(user)
    }

    fun getUserCount(): Int = users.size
}

fun main() {
    val app = main()
    app.initialize()
    app.run()
    println("Total users: \${app.getUserCount()}")
}

# Setup Update 1760680246

# Setup Update 1760680246

# Setup Update 1760680246

# Setup Update 1760680246

# Setup Update 1760680247

# Setup Update 1760680247

# Setup Update 1760680247

# Setup Update 1760680247

# Setup Update 1760680247

# Setup Update 1760680247

# Setup Update 1760680247

# Setup Update 1760680247

# Setup Update 1760680247

# Setup Update 1760680247

# Setup Update 1760680248
